myData <-read.csv("moviedb.csv", header = TRUE)
str(myData)
library(fpc)
library(wskm)
library(rgl)
library(cba)
library(cluster)
rc <- rockCluster(myData, n=2, theta=0.8, debug=TRUE)
plot3d(myData[c("title", "genre")], col=rc$cl)